services:
  HeimrichHannot\ContaoFilterChoiceRangeBundle\EventListener\AfterChoiceGetOptionsEventListener:
    tags:
      - { name: kernel.event_listener, event: huh.filter.event.adjust_filter_options_event, method: setUptRangeFieldOptions }